# Generated by Django 6.0.2 on 2026-03-10 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_alter_marketplaceitem_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="marketplace.marketplacecategory",
            ),
        ),
    ]
