# Generated by Django 6.0.2 on 2026-03-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0004_alter_skill_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="skills", to="skills.skillcategory"
            ),
        ),
    ]
